export const RECEIVE_ARTICLES = 'RECEIVE_ARTICLES';
export const SEND_NEW_ARTICLE = 'SEND_NEW_ARTICLE';
export const UPDATE_ARTICLE = 'UPDATE_ARTICLE';
export const DELETE_ARTICLE = 'DELETE_ARTICLE';
export const REFRESH_ARTICLES = 'REFRESH_ARTICLES';
